name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t action
      - name: Push to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG=docker.pkg.github.com/$GITHUB_REPOSITORY/action:$(echo $GITHUB_REF | sed -e 's:refs/\(head\|tag\)s/::g')
          docker tag action "$TAG"
          docker push "$TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
